<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [2]:
import glob
from ase.io import read
import re 
import numpy as np 
# from np.vizualize import 

In [3]:
files = glob.glob('LAMMPS*.POSCAR')
files 

['LAMMPS_HEA_17.POSCAR',
 'LAMMPS_HEA_83.POSCAR',
 'LAMMPS_HEA_110.POSCAR',
 'LAMMPS_HEA_114.POSCAR']

In [4]:
f = open('readme.txt')
lines = f.readlines()
frames = {}
for iline, line in enumerate(lines):
    if 'in frame' in line: 
        data1 = re.findall(r"[-+]?\d*\.\d+|\d+", line )
        data2 = [ float(x) for x in re.findall(r"[-+]?\d*\.\d+|\d+", lines[iline+1] )]
        frames[data1[0]]= np.array(data2).reshape(-1,3)

IndexError: list index out of range

In [13]:
frames

{'12': array([[7.82436, 4.33866, 5.55284],
        [9.76322, 3.27861, 5.32413]]),
 '17': array([[7.2849 , 4.56472, 5.58142],
        [7.04522, 6.20651, 5.30631]]),
 '23': array([[7.27454, 3.53009, 6.20793],
        [7.06915, 3.53511, 8.35177]]),
 '35': array([[6.42019, 3.37433, 5.56198],
        [4.30621, 3.85243, 5.08817]]),
 '114': array([[8.05339  , 0.       , 4.40405  ],
        [3.       , 7.1804   , 0.       ],
        [6.46739  , 0.0557286, 7.29133  ]])}

In [79]:
atms = [ read(file) for file in files ]

In [83]:
np.where(atms[4].positions == 7.82436)

(array([], dtype=int64), array([], dtype=int64))

In [64]:
distances = atms[0].get_all_distances()
distances.shape

(865, 865)

In [70]:
Min_Inter_Atomic_Distance = min(distances[0][1:len(distances)])
Min_Inter_Atomic_Distance

2.5082649646717945

In [71]:
np.where(distances==2.5082649646717945)

(array([0, 2]), array([2, 0]))

In [73]:
print(distances[0][2])

2.5082649646717945


In [76]:
print(atm.positions[0])
print(atm.positions[2])

[1.7754981  3.63447637 1.84730901]
[1.8087681  5.40862637 3.62006901]


In [78]:
atm.del

SyntaxError: invalid syntax (199590501.py, line 1)